# Generated by Django 4.0.5 on 2022-06-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_city_profile_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('gerente', 'Ger'), ('operador', 'Op')], max_length=20),
        ),
    ]
