# Generated by Django 4.0.5 on 2022-07-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('gerente', 'Ger'), ('operador', 'Op'), ('participante', 'Par')], max_length=20),
        ),
    ]
