# Generated by Django 4.0.5 on 2022-06-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='createdAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='fechaFin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
    ]
