# Generated by Django 4.0.5 on 2022-06-23 22:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='capacity',
            new_name='aforo',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='place',
            new_name='lugar',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='events',
            name='contacto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='createdBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='disponible',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 22, 38, 1, 797987, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 22, 38, 10, 88068, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='gmaps',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
