# Generated by Django 4.0.5 on 2022-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_createdat_alter_events_fechafin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='contacto',
            field=models.TextField(default=''),
        ),
    ]
