# Generated by Django 4.0.5 on 2022-06-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
