# Generated by Django 4.0.5 on 2022-07-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_contacto'),
        ('participants', '0005_alter_devolution_table'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='idEvent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='events.events'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.CreateModel(
            name='ActivityInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('I', 'Inscrito'), ('NI', 'No Inscrito')], max_length=2)),
                ('idActivity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activities.activity')),
                ('idParticipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
            options={
                'db_table': 'activity_inscription',
            },
        ),
    ]
