# Generated by Django 4.0.4 on 2022-06-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='pub_date',
            new_name='publishedAt',
        ),
    ]
