# Generated by Django 4.0.4 on 2022-06-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_news_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
