# Generated by Django 4.0.4 on 2022-06-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_rename_created_by_news_createdby_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
