# Generated by Django 4.0.4 on 2022-06-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_news_description_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
