# Generated by Django 4.0.5 on 2022-07-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_alter_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publishedAt',)},
        ),
    ]
