# Generated by Django 4.0.5 on 2022-07-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_createdat_alter_events_fechafin_and_more'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PI', 'Pre Inscrito'), ('I', 'Inscrito'), ('C', 'Cancelado'), ('D', 'Devolucion')], max_length=2)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.events')),
                ('id_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
            options={
                'db_table': 'event_inscription',
            },
        ),
    ]
