# Generated by Django 4.0.5 on 2022-07-11 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_eventinscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinscription',
            old_name='id_event',
            new_name='idEvent',
        ),
        migrations.RenameField(
            model_name='eventinscription',
            old_name='id_participant',
            new_name='idParticipant',
        ),
        migrations.AddField(
            model_name='eventinscription',
            name='registerDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 3, 35, 46, 747145, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
