# Generated by Django 4.0.5 on 2022-07-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_rename_id_event_eventinscription_idevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinscription',
            name='status',
            field=models.CharField(choices=[('I', 'Inscrito'), ('C', 'Cancelado'), ('D', 'Devolucion')], max_length=2),
        ),
        migrations.CreateModel(
            name='Devolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('solicitudDate', models.DateTimeField()),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.eventinscription')),
            ],
        ),
    ]
