# Generated by Django 4.0.5 on 2022-07-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_eventinscription_status_devolution'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devolution',
            table='devolution',
        ),
    ]
